import { StrictMode, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import * as XLSX from 'xlsx';
import './styles.css';

const API = '/api';
const formatNumber = (value) => new Intl.NumberFormat('vi-VN').format(value || 0);
const rate = (signed, total) => total ? `${(signed / total * 100).toFixed(1).replace('.', ',')}%` : '—';
const dateText = (value) => value || '—';

function App() {
  const [page, setPage] = useState('import'); const [imports, setImports] = useState([]); const [selectedId, setSelectedId] = useState(null); const [report, setReport] = useState(null); const [preview, setPreview] = useState([]); const [uploading, setUploading] = useState(false); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [sort, setSort] = useState('total'); const [showRules, setShowRules] = useState(false); const [rules, setRules] = useState(null);
  const loadImports = async () => { const data = await (await fetch(`${API}/imports`)).json(); setImports(data); if (!selectedId && data[0]) setSelectedId(data[0].id); };
  useEffect(() => { loadImports(); fetch(`${API}/rules`).then((r) => r.json()).then(setRules); }, []);
  useEffect(() => { if (!selectedId) return; fetch(`${API}/imports/${selectedId}/report`).then((r) => r.json()).then(setReport); }, [selectedId]);
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setError(''); const form = new FormData(); form.append('file', file); try { const response = await fetch(`${API}/imports`, { method: 'POST', body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setPreview(data.preview); setSelectedId(data.import.id); setImports((current) => [data.import, ...current]); setPage('report'); } catch (cause) { setError(cause.message); } finally { setUploading(false); event.target.value = ''; } };
  const saveRules = async () => { const response = await fetch(`${API}/rules`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(rules) }); const data = await response.json(); setRules(data); setShowRules(false); if (selectedId) setReport(await (await fetch(`${API}/imports/${selectedId}/report`)).json()); };
  const records = useMemo(() => (report?.records || []).filter((item) => item.unit.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi'))).sort((a, b) => sort === 'name' ? a.unit.localeCompare(b.unit, 'vi') : sort === 'signed' ? b.signed / b.total - a.signed / a.total : b.total - a.total), [report, query, sort]);
  const download = () => { if (!report) return; const rows = report.records.map((item, index) => ({ STT: index + 1, 'Đơn vị': item.unit, 'BC/TTr - Đã ký': item.report[0], 'BC/TTr - Tổng': item.report[1], 'CV/UQ - Đã ký': item.letter[0], 'CV/UQ - Tổng': item.letter[1], 'Thư công tác - Đã ký': item.work[0], 'Thư công tác - Tổng': item.work[1], 'Tổng đã ký': item.signed, 'Tổng văn bản': item.total })); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, XLSX.utils.json_to_sheet(rows), 'Thong ke'); XLSX.writeFile(book, 'Thong_ke_van_ban_iOffice.xlsx'); };
  return <><header className="topbar"><button className="brand" onClick={() => setPage('import')}><span>iO</span>iOffice <i>/ Rà soát</i></button><nav><button className={page === 'import' ? 'active' : ''} onClick={() => setPage('import')}>01 · Nhập dữ liệu</button><button className={page === 'report' ? 'active' : ''} onClick={() => setPage('report')}>02 · Kết quả tổng hợp</button></nav><select className="import-select" value={selectedId || ''} onChange={(e) => { setSelectedId(Number(e.target.value)); setPage('report'); }}><option value="">Chọn lần nhập</option>{imports.map((item) => <option key={item.id} value={item.id}>#{item.id} · {item.file_name}</option>)}</select></header><main>{page === 'import' ? <ImportPage upload={upload} uploading={uploading} error={error} preview={preview} setPage={setPage} setShowRules={setShowRules} /> : <ReportPage report={report} records={records} query={query} setQuery={setQuery} sort={sort} setSort={setSort} download={download} setPage={setPage} />}</main>{showRules && rules && <Rules rules={rules} setRules={setRules} close={() => setShowRules(false)} save={saveRules} />}</>;
}
function ImportPage({ upload, uploading, error, preview, setPage, setShowRules }) { return <section><div className="hero"><div><p className="eyebrow">TRANG 01 · NGUỒN DỮ LIỆU</p><h1>Nhập văn bản đi từ iOffice</h1><p>File được lưu trong cơ sở dữ liệu nội bộ để tạo báo cáo, đối chiếu và tra cứu lại sau này.</p></div><div className="note"><b>SQLite</b><span>Lưu lịch sử import và rule</span></div></div><div className="import-grid"><label className="dropzone"><input type="file" accept=".xlsx,.xls" onChange={upload} /><span className="upload-icon">↑</span><strong>{uploading ? 'Đang nhập dữ liệu…' : 'Chọn file Excel đầu vào'}</strong><span>Kéo thả file hoặc bấm để duyệt</span><small>Cần các cột: Trích yếu, Số ký hiệu, Văn bản ký số, Ngày ban hành, Đơn vị ban hành.</small></label><aside className="rule-card"><p className="eyebrow">QUY TẮC PHÂN LOẠI</p><ol><li><b>BC</b> hoặc <b>TTr</b> → Báo cáo / Tờ trình</li><li><b>CV</b> hoặc <b>UQ</b> → Công văn / Ủy quyền</li><li>Còn lại → Thư công tác</li><li><b>NHNo/Agribank</b> → Công văn; đơn vị lấy mã sau dấu <b>-</b>.</li></ol><button className="link-button" onClick={() => setShowRules(true)}>Điều chỉnh quy tắc →</button></aside></div>{error && <p className="error">{error}</p>}{preview.length > 0 && <div className="preview"><div><p className="eyebrow">ĐÃ NHẬP THÀNH CÔNG</p><h2>Xem trước 8 dòng đầu</h2></div><button className="primary" onClick={() => setPage('report')}>Mở báo cáo →</button><div className="table-wrap"><table><thead><tr>{Object.keys(preview[0]).map((key) => <th key={key}>{key}</th>)}</tr></thead><tbody>{preview.map((row, index) => <tr key={index}>{Object.entries(row).map(([key, value]) => <td key={key}>{String(value)}</td>)}</tr>)}</tbody></table></div></div>}</section>; }
function ReportPage({ report, records, query, setQuery, sort, setSort, download, setPage }) { if (!report) return <div className="empty"><h2>Chưa chọn dữ liệu</h2><p>Hãy nhập file Excel trước để xem báo cáo.</p><button className="primary" onClick={() => setPage('import')}>Nhập dữ liệu</button></div>; const { totals } = report; return <section><div className="report-head"><div><p className="eyebrow">TRANG 02 · KẾT QUẢ</p><h1>Thống kê văn bản đi theo đơn vị</h1><p>Khoảng thời gian: {dateText(report.period.from)} – {dateText(report.period.to)} · Lần nhập #{report.import.id}</p></div><div><button className="secondary" onClick={download}>Tải Excel</button><button className="primary" onClick={() => setPage('import')}>Nhập file mới</button></div></div><div className="metrics"><Metric label="Tổng văn bản" value={totals.total} accent /><Metric label="Đã ký số" value={totals.signed} /><Metric label="Công văn / Ủy quyền" value={totals.letter} /><Metric label="Thư công tác" value={totals.work} /></div><div className="toolbar"><input placeholder="⌕  Tìm đơn vị" value={query} onChange={(e) => setQuery(e.target.value)} /><select value={sort} onChange={(e) => setSort(e.target.value)}><option value="total">Sắp xếp: Tổng văn bản</option><option value="name">Sắp xếp: Tên đơn vị</option><option value="signed">Sắp xếp: Tỷ lệ ký số</option></select><span>{records.length} đơn vị</span></div><div className="table-wrap report-table"><table><thead><tr><th rowSpan="2">STT</th><th rowSpan="2">Đơn vị</th><th colSpan="3">Báo cáo / Tờ trình</th><th colSpan="3">Công văn / Ủy quyền</th><th colSpan="3">Thư công tác</th><th colSpan="3" className="total">Tổng văn bản</th></tr><tr>{Array.from({ length: 4 }).flatMap((_, index) => ['Đã ký', 'Tổng', 'Tỷ lệ'].map((label) => <th key={`${index}-${label}`}>{label}</th>))}</tr></thead><tbody>{records.map((row, index) => <tr key={row.unit}><td>{index + 1}</td><td>{row.unit}</td><Cells pair={row.report} /><Cells pair={row.letter} /><Cells pair={row.work} /><td>{formatNumber(row.signed)}</td><td>{formatNumber(row.total)}</td><td>{rate(row.signed, row.total)}</td></tr>)}</tbody></table></div></section>; }
function Metric({ label, value, accent }) { return <div className={`metric ${accent ? 'accent' : ''}`}><b>{formatNumber(value)}</b><span>{label}</span></div>; }
function Cells({ pair }) { return <><td>{formatNumber(pair[0])}</td><td>{formatNumber(pair[1])}</td><td className="rate">{rate(pair[0], pair[1])}</td></>; }
function Rules({ rules, setRules, close, save }) { const edit = (key, value) => setRules({ ...rules, [key]: value.split(',').map((item) => item.trim()).filter(Boolean) }); return <div className="modal"><div className="modal-card"><button className="close" onClick={close}>×</button><p className="eyebrow">CẤU HÌNH</p><h2>Quy tắc xử lý</h2><p>Từ khóa cách nhau bằng dấu phẩy; thay đổi được lưu trong cơ sở dữ liệu.</p><label>Báo cáo / Tờ trình<input value={rules.report.join(',')} onChange={(e) => edit('report', e.target.value)} /></label><label>Công văn / Ủy quyền<input value={rules.letter.join(',')} onChange={(e) => edit('letter', e.target.value)} /></label><label>Đơn vị Agribank đặc biệt<input value={rules.agribank.join(',')} onChange={(e) => edit('agribank', e.target.value)} /></label><div className="actions"><button className="secondary" onClick={close}>Hủy</button><button className="primary" onClick={save}>Lưu quy tắc</button></div></div></div>; }
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
